name: Update channels

on:
  workflow_dispatch:
  schedule:
    - cron: '33 3 * * *' # runs daily at 03:33

permissions: {}

jobs:
  update-channel:
    name: Update (${{ matrix.flake-directory }})

    concurrency:
      group: update-channel-${{ matrix.flake-directory }}
      cancel-in-progress: false

    strategy:
      matrix:
        flake-directory: [
          "partitions/channels/nixos",
          "partitions/channels/nixos-small",
          "partitions/channels/nixos-unstable",
          "partitions/channels/nixos-unstable-small",
          "partitions/channels/nixpkgs-darwin",
          "partitions/channels/nixpkgs-unstable"
        ]

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: true

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@bafaa638b9d5ec0e7e3ac1a7fc80453ef1fd265f # v3

      - name: Update flake lock
        id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@5ba4a20ae344a5edd7b97ed3002219974f4d20d7 # main
        with:
          commit-msg: "chore(${{ matrix.flake-directory }}): update flake.lock"
          pr-title: "Update ${{ matrix.flake-directory }}/flake.lock"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: |
            dependencies
            automated
          path-to-flake-dir: '${{ matrix.flake-directory }}'
          branch: "update_flake_lock_${{ strategy.job-index }}"

      - name: Enable PR auto-merge
        if: steps.update-flake-lock.outputs.pull-request-number != ''
        run: gh pr merge --auto --rebase --delete-branch "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.update-flake-lock.outputs.pull-request-number }}
